"""Central configuration for the Dark Patterns Audit Tool."""

from __future__ import annotations

import os
from pathlib import Path

# Paths
PROJECT_ROOT = Path(__file__).parent.parent
ONTOLOGY_PATH = PROJECT_ROOT / "config" / "ontology.json"

# Model
MODEL = "claude-sonnet-4-20250514"
TEMPERATURE = 0.1
MAX_TOKENS = 4096

# Ontology
ONTOLOGY_VERSION = "1.0"

# App
APP_TITLE = "Dark Patterns Audit Tool"
APP_SUBTITLE = "Powered by the Gray et al. (2024) CHI Dark Pattern Ontology"
MAX_FILE_SIZE_MB = 10
ALLOWED_IMAGE_TYPES = ["png", "jpg", "jpeg", "webp"]

# Severity
SEVERITY_LEVELS = ["High", "Medium", "Low"]
SEVERITY_COLORS = {
    "High": "#F6A4B7",
    "Medium": "#FDB633",
    "Low": "#18A48C",
}
RISK_LEVEL_COLORS = {
    "High": "#F6A4B7",
    "Medium": "#FDB633",
    "Low": "#18A48C",
    "Clean": "#000000",
}

# Export
REPORT_FOOTER = "Generated by BIT Dark Patterns Audit Tool v1.0"


def get_api_key() -> str | None:
    """Get Anthropic API key from environment or Streamlit secrets."""
    from pathlib import Path
    from dotenv import load_dotenv
    load_dotenv(Path(__file__).parent.parent / ".env", override=True)
    key = os.environ.get("ANTHROPIC_API_KEY")
    if key:
        return key
    try:
        import streamlit as st
        return st.secrets.get("ANTHROPIC_API_KEY")
    except Exception:
        return None
